### ISSUE TITLE
homebridge crashes with "RangeError"

### ISSUE THREAD

**Issue by djh1202** [tattn/homebridge-rm-mini3#1]
I'm probably screwing something up: I've installed the plugin and have homebridge running, but when I try switch the accessory on or off, homebridge crashes with the following error:

dgram.js:273
    throw new RangeError('Offset + length beyond buffer length');
    ^

RangeError: Offset + length beyond buffer length
    at Socket.send (dgram.js:273:11)
    at module.exports (/usr/local/lib/node_modules/homebridge-rm-mini3/sender.js:12:10)
    at Object.RMMini3Accessory.setPowerState (/usr/local/lib/node_modules/homebridge-rm-mini3/index.js:29:7)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:155:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:727:22)
    at Array.forEach (native)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:672:8)
    at emitMany (events.js:108:13)

**Comment by tattn** [comment]
@djh1202
Sorry, It's a bug. 
Now, I fixed the bug.
Please update the plugin and retry :-)

**Comment by djh1202** [comment]
I'm still getting the error...

**Comment by djh1202** [comment]
I updated the package but I'm still getting this same error? suggestions?
