### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jat80** [tattn/homebridge-rm-mini3#3]
I think i've installed it right.  Had to remove the final , after line 31 on the .json file as it was validating correctly but after loading up it gives me this at the end and the accessory is unresponsive on the home app.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:10)

**Comment by tattn** [comment]
Something is already running on port 51826?

the same error:
https://github.com/nfarina/homebridge/issues/698
